var nome1 = prompt("Digite o nome da primeira pessoa: ")
var nome2 = prompt("Digite o nome da segunda pessoa: ")
var nome3 = prompt("Digite o nome da terceira pessoa: ")
var nome4 = prompt("Digite o nome da quarta pessoa: ")
var idade1 = prompt("Digite a idade da primeira pessoa: ")
var idade2 = prompt("Digite a idade da segunda pessoa: ")
var idade3 = prompt("Digite a idade da terceira pessoa: ")
var idade4 = prompt("Digite a idade da quarta pessoa: ")
idade1 = parseInt(idade1)
idade2 = parseInt(idade2)
idade3 = parseInt(idade3)
idade4 = parseInt(idade4)
var media = (idade1+idade2+idade3+idade4)/4
alert(media)