var a = parseInt(prompt("Digite o primeiro número: "))
var b = parseInt(prompt("Digite o segundo número: "))
var c = parseInt(prompt("Digite o terceiro número: "))
var d = parseInt(prompt("Digite o quarto número: "))
var e = parseInt(prompt("Digite o quinto número: "))
alert("A ordem orignal dos números é: ")
alert(a)
alert(b)
alert(c)
alert(d)
alert(e)
var f = b
b = d
d = f
alert("A ordem trocada dos números é: ")
alert(a)
alert(b)
alert(c)
alert(d)
alert(e)